automation:

- alias: Luce notturna corridoio on
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00020dee74
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - after: '22:30'
    before: 07:30
    condition: time
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.gateway_light_7811dce17669
      rgb_color:
      - 255
      - 255
      - 255
      brightness_pct: 100

- alias: Luce notturna corridoio off
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00020dee74
    platform: state
    from: 'on'
    to: 'off'
  condition:
  - after: '22:30'
    before: 07:30
    condition: time
  action:
  - data:
      transition: 60
    entity_id:
    - light.gateway_light_7811dce17669
    service: light.turn_off
- alias: Illuminazione Bagno Al Max
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001e5cbeb
      click_type: long_click_press
  action:
  - service: light.turn_on
    data:
      entity_id: light.plafoniera_bagno
      brightness: 255
      kelvin: 4500

- alias: Illuminazione Bagno
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001e5cbeb
      click_type: single
  action:
  - service: light.toggle
    data:
      entity_id: light.plafoniera_bagno
      brightness: 80
      kelvin: 6500

- alias: Toggle off Yeelight Letto
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002131344
      click_type: double
  condition:
  - condition: state
    entity_id: light.yeelight_letto
    state: 'on'
  action:
  - data:
      entity_id: light.yeelight_letto
    service: light.turn_off

- alias: Toggle on Yeelight Bimbi
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002131344
      click_type: double
  condition:
  - condition: state
    entity_id: light.yeelight_bimbi
    state: 'off'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.yeelight_bimbi
      kelvin: 4000
      brightness_pct: 100

- alias: Camera Bimbi Nightlight
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002131344
      click_type: single
  action:
  - service: light.turn_on
    entity_id:
    - light.yeelight_bimbi
    data_template:
      brightness_pct: 30
      color_name: >
        {% set colors = ['red', 'yellow', 'blue', 'green', 'purple', 'fuchsia'] %}
        {{ colors|random }}
      
- alias: Illuminazione Faretti Cucina
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002131396
      click_type: single
  action:
  - service: light.toggle
    data:
      entity_id: group.faretti_cucina
      brightness: 255
      kelvin: 6500

- alias: Accendi Faretti Cucina Al Max
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0002131396
      click_type: double
  action:
  - service: light.turn_on
    data:
      entity_id: light.faretto_cucina_2
      brightness: 255
      kelvin: 4500 
      
- alias: Porta Blindata Aperta
  hide_entity: true
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.door_window_sensor_158d000203052a
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    state: not_home
    entity_id: group.dss_dispositivi_user1
  - condition: state
    state: not_home
    entity_id: group.dss_dispositivi_user2
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.dafang
      filename: /tmp/ip_webcam.jpg
  - service: notify.notifiche_telegram
    data:
      message: 📸 Foto Blindata Aperta
      data:
        photo:
          url: https://xxxxxxxxxxxxx.duckdns.org:8123{{states.camera.dafang.attributes.entity_picture}}
          caption: Porta Blindata Aperta {{ now().strftime( '%Y-%m-%d %H:%M:%S') }}

  - service: camera.record
    data:
      entity_id: camera.dafang
      filename: /config/www/temp/{{ entity_id }}_{{ now().strftime("%Y%m%d-%H%M%S")
        }}.mp4
      duration: 10
      lookback: 30
  - delay:
      seconds: 20
  - service: notify.notifiche_telegram
    data:
      message: 📽️ Video Porta Blindata
      data:
        video:
        - url: https://xxxxxxxxxxx.duckdns.org:8123/local/temp/{{ entity_id }}_{{ now().strftime("%Y%m%d-%H%M%S")}}.mp4
          timeout: 69
          caption: Video Porta Blindata {{ now().strftime( '%Y-%m-%d %H:%M:%S') }}