
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/


burze_api_key: 'e49891xxxxxxxxxxxxxxxxxxxxf6467'
istat: '033037'
regione: Emilia e Romagna
tuya_username: inxxxxxxxx@xxxxx.it
tuya_password: xxxxxxxx
google_user: 8xxxxxxxxgmail.com
google_password: xxxxxxxxxx
tuya_country: +39 
google_maps_username: hoxxxxxxxxxxxx@gmail.com
google_maps_password: xxxxxxxxxxxxxxxx


snapv: ffmpeg -rtsp_transport tcp -r 25 -i rtsp://root:xxxxxxxxxxxxxx@192.168.1.150:10554/tcp/av0_0 -an -t 10 -c copy -map 0 -y -update 1 {{filename}}
rtsp_input: -rtsp_transport tcp -i rtsp://root:xxxxxxxxxxxxx@192.168.1.150:8554/unicast
entity_amazon_echo_id: media_player.echo_dot_di_ingrid
amazon_user: xxxxxxxxxxxxxx@yyyyyy.it
amazon_password: yyyyyyyyy


darksky_api_key: 99xxxxxxxxxxxxxxxxxxxxxxxxxxxxe
latitude_home: xx.xxxx
longitude_home: y.yyyyyy

api_key_google: AIzxxxxxxxxxxxxxxxxxxxxxxxx
ifttt_api: bxxxxxxxxxxxxxxxxxxxx

chat_id1: 57xxxxxxxxxx
chat_id2: 21xxxxxxxxxx
allowed_chat_ids: 57xxxxxxx
allowed_chat_ids2: 21xxxxxxxx
psw_AutoBackup: xxxxxxxxxxxxxx

gateway1_token: 9e4usxxxxxxxxxxxxxxxxx
#xiaomi_gateway1_mac: 78:11:dc:e1:76:69
2_gateway1_token: mpxxxxxxxxxxxxxx
2_xiaomi_gateway1_mac: 7C:49:EB:88:F1:D1
xiaomi_gateway2_mac: 7C:49:EB:88:F1:D1

entity_luce_gateway: light.gateway_light_7811dce17669
entity_cubo_aqara: binary_sensor.cube_158d00027cee95
#entity_light_gateway1: light.gateway_light_7811dce17669
entity_pulsante_bagno: binary_sensor.switch_158d0001e5cbeb
entity_pulsante_cucina: binary_sensor.switch_158d0002131396

entity_sensore_blindata: binary_sensor.door_window_sensor_158d000203052a
entity_sensore_fin_salotto: binary_sensor.door_window_sensor_158d000221825a
entity_sensore_fin_letto: binary_sensor.door_window_sensor_158d000202ddff
entity_sensore_fin_letto_bimbi: binary_sensor.door_window_sensor_158d0002254081
entity_sensore_fin_cucina: binary_sensor.door_window_sensor_158d0001f39528
entity_sensore_mod: binary_sensor.door_window_sensor_158d0001e64513
#entity_pulsante_com_user1: binary_sensor.switch_158d00021313e1
entity_pulsante_com_user2: binary_sensor.switch_158d0002131344
#entity_pulsante_ingresso: binary_sensor.switch_158d000228651e
entity_sensore_acqua: binary_sensor.water_leak_sensor_158d0002138b66
entity_sensore_temp_esterna: sensor.temperature_158d00022c757b
entity_sensore_temp_interna: sensor.temperature_158d00022c75fa
entity_sensore_fin_bagno: binary_sensor.door_window_sensor_158d0001f9e58a
entity_sensore_fin_scala: binary_sensor.door_window_sensor_158d0002536dab

temp_camera_letto: sensor.temperature_158d00022c75fa

sensori_umidita: [
sensor.humidity_158d00022c75fa,
sensor.humidity_158d000272fe6a,
sensor.humidity_158d00023d4fca,
sensor.salotto_humidity,
sensor.humidity_158d0002741c97,
sensor.umidita_smarther
]

umidita_camera_letto: sensor.humidity_158d00022c75fa
umidita_camera_bimbi: sensor.humidity_158d000272fe6a
umidita_bagno: sensor.humidity_158d00023d4fca
umidita_salotto: sensor.salotto_humidity
umidita_scala: sensor.humidity_158d0002b5c9bf
umidita_cucina: sensor.humidity_158d0002741c97
umidita_smarther: sensor.umidita_smarther


#entity_sensore_fin_scala: 
#entity_sensore_body_corridoio_notte: 
#entity_sensore_body_cucina:
entity_sensore_body_salotto: binary_sensor.motion_sensor_158d0001e5238b
entity_sensore_body_bagno: binary_sensor.motion_sensor_158d00020dee74
entity_sensore_body_scala: binary_sensor.motion_sensor_158d0001f9d4ee
url_snapshot_camera: https://wwwwwwwwwww.duckdns.org:8123{{states.camera.dafang.attributes.entity_picture}}

multipresa1_sw1: 
multipresa1_sw2: 
multipresa1_sw3: 
multipresa1_sw4: 
multipresa1_sw7: 

### Queste le key da personalizzare ed inserire nel file secrets.yaml

############ DSS XIAOMI ALARM #############

### MAC Address del primo Gateway Xiaomi. Notare la mancanza di separatori (:) e la scrittura in minuscolo.
xiaomi_gateway1_mac: 78:11:dc:e1:76:69

# ### se avete ulteriori gateway dovete inserirne i mac address
# ### xiaomi_gateway2_mac: 22xx222x33xx


# ### URL di un'immagine da associare agli utenti tracciati
url_immagine_profilo_user1: /local/immagini/ingrid.jpg
url_immagine_profilo_user2: /local/immagini/xxxxxx.jpg
url_immagine_profilo_user3: https://www.life360.com/img/user_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxe09-ae5f-yyyyyyyyyyyyyyyyg?fd=2
url_immagine_profilo_user4: https://www.life360.com/img/user_images/1xxxxxxxxxxxxxxxxxxxxxxxxxxx1-ff99-4d25yyyyyyyyyyy.png?fd=2

### se avete ulteriori utenti, definite anche le loro immagini. Nulla vi vieta di usare immagini locali
### url_immagine_profilo_user3: "/local/www/foto.jpg"

### Entity_id della luce del Gateway1
entity_light_gateway1: light.gateway_light_7811dce17669

### se avete ulteriori gateway... sapete cosa fare

### Entity_id di un sensore o di un gruppo di sensori che al cambio di stato da OFF ad ON, in caso di allarme attivo, farà riprodurre un avviso di allarme ATTIVO.
### Notate che è possibile usare un entity_id singolo o un array. Se non si desidera utilizzare tale funzionalità basterà inserire un array vuoto: [ ]
entity_sensore_promemoria_allarme_attivato_away: binary_sensor.motion_sensor_158d0001e5238b

entity_sensore_promemoria_allarme_attivato_home: binary_sensor.door_window_sensor_158d000203052a

### Entity_id di un sensore o di un gruppo di sensori che al cambio di stato da OFF ad ON, in caso di allarme attivo, farà riprodurre un avviso di allarme ATTIVO e DOPO 30 secondi farà innescare l'allarme.
entity_sensore_innesco_ritardato_allarme_away: [
binary_sensor.door_window_sensor_158d000203052a,
binary_sensor.motion_sensor_158d0001f9d4ee,
binary_sensor.motion_sensor_158d0001e5238b,
binary_sensor.motion_sensor_158d00020dee74
]
entity_sensore_innesco_ritardato_allarme_home: []

### Entity_id di un sensore o di un gruppo di sensori che, in fase di attivazione dell'allarme non dovranno essere considerati nel controllo dell'apertura. 
### Cioè non ne verrà segnalata l'apertura mediante avvisi luminosi, TTS o Notifiche (Telegram e/o HTML5)
### ATTENZIONE: se non deve essere ignorata nessuna entity_id, assicurati di mettere almeno un valore. es: ['Nessuna']
dss_binary_sensor_secrets_ignora_controllo_infissi_chiusi_home: ['Nessuno']

dss_binary_sensor_secrets_ignora_controllo_infissi_chiusi_away: [
binary_sensor.door_window_sensor_158d000203052a,
binary_sensor.door_window_sensor_158d0001e64513
]

### Entity_id di un sensore o di un gruppo di sensori che, in fase di attivazione dell'allarme non dovranno essere considerati nel controllo luci accese. 
### Cioè non ne verrà segnalata l'apertura mediante Notifiche (Telegram e/o HTML5)
### ATTENZIONE: se non deve essere ignorata nessuna entity_id, assicurati di mettere almeno un valore. es: ['Nessuna']

dss_binary_sensor_secrets_ignora_controllo_luci_accese_home: [
switch.dafang_blue_led,
switch.dafang_h264_rtsp_server,
switch.dafang_ir_filter,
switch.dafang_ir_led,
switch.dafang_mjpeg_rtsp_server,
switch.dafang_motion_detection,
switch.dafang_motion_send_mail,
switch.dafang_motion_send_telegram,
switch.dafang_motion_tracking,
switch.dafang_night_mode,
switch.dafang_night_mode_auto,
switch.dafang_yellow_led
]
dss_binary_sensor_secrets_ignora_controllo_luci_accese_away: [
light.gateway_light_7811dce17669,
switch.dafang_blue_led,
switch.dafang_h264_rtsp_server,
switch.dafang_ir_filter,
switch.dafang_ir_led,
switch.dafang_mjpeg_rtsp_server,
switch.dafang_motion_detection,
switch.dafang_motion_send_mail,
switch.dafang_motion_send_telegram,
switch.dafang_motion_tracking,
switch.dafang_night_mode,
switch.dafang_night_mode_auto,
switch.dafang_yellow_led
]

### Entity_id di un sensore o di un gruppo di sensori che, in fase di attivazione dell'allarme non dovranno essere considerati nel controllo climatizzatore acceso. 
### Cioè non ne verrà segnalata l'apertura mediante Notifiche (Telegram e/o HTML5)
### ATTENZIONE: se non deve essere ignorata nessuna entity_id, assicurati di mettere almeno un valore. es: ['Nessuna']
dss_binary_sensor_secrets_ignora_controllo_clima_acceso_home: [
climate.rpi_cooling_fan_controller,
climate.daikin_stylish,
climate.smarther
]

dss_binary_sensor_secrets_ignora_controllo_clima_acceso_away: [
climate.rpi_cooling_fan_controller,
climate.daikin_stylish,
climate.smarther
]

### Entity_id di un sensore o di un gruppo di sensori che attivano/disattivano l'allarme. 
### Ovviamente sarà possibile specificare entity_id singoli, gruppi (mediante array [ ]), o array vuoti ([ ]).


entity_pulsante_attiva_allarme_home: binary_sensor.switch_158d00021313e1
entity_pulsante_attiva_allarme_away: binary_sensor.switch_158d000228651e

### Entity_id di un sensore o di un gruppo di sensori che innescano l'allarme se attivo in modalità HOME. 
sensori_che_fanno_scattare_allarme_home_mode: [
binary_sensor.door_window_sensor_158d000203052a, 
binary_sensor.door_window_sensor_158d000221825a, 
binary_sensor.door_window_sensor_158d000202ddff,
binary_sensor.door_window_sensor_158d0002254081,
binary_sensor.door_window_sensor_158d0001f39528,
binary_sensor.door_window_sensor_158d0001f9e58a,
binary_sensor.door_window_sensor_158d0002536dab
]

### Entity_id di un sensore o di un gruppo di sensori che innescano l'allarme se attivo in modalità AWAY. 
sensori_che_fanno_scattare_allarme_away_mode: [
binary_sensor.door_window_sensor_158d000203052a, 
binary_sensor.door_window_sensor_158d000221825a, 
binary_sensor.door_window_sensor_158d000202ddff,
binary_sensor.door_window_sensor_158d0002254081,
binary_sensor.door_window_sensor_158d0001f39528,
binary_sensor.door_window_sensor_158d0001f9e58a,
binary_sensor.door_window_sensor_158d0002536dab,
binary_sensor.motion_sensor_158d0001e5238b,
binary_sensor.motion_sensor_158d00020dee74,
binary_sensor.motion_sensor_158d0001f9d4ee
]



### Nome del Gruppo dei dispositivi dell'utente 1. Deve cominciare con "Dispositivi "
nome_gruppo_dispositivi_utente1: "Dispositivi Ingrid" 
### Entity_id di un device_tracker o di un gruppo di device_tracker che devono essere tracciati per l'utente 1. 
elenco_dispositivi_tracciati_user1: [
device_tracker.google_maps_116716013753767492736,
device_tracker.life360_ingrid,
device_tracker.oneplus_6_fritz_box,
device_tracker.oneplus_6,
device_tracker.amazfit_pace,
sensor.tracker_itag_ingrid,
sensor.tracker_nut_user1,
sensor.amazfit_esp32,
sensor.tracker_itag_casa,
device_tracker.nut_mini_ingrid
]

### Nome del Gruppo dei dispositivi dell'utente 1. Deve cominciare con "Dispositivi "
nome_gruppo_dispositivi_utente2: "Dispositivi xxxxxxxx"
### Entity_id di un device_tracker o di un gruppo di device_tracker che devono essere tracciati per l'utente 2
elenco_dispositivi_tracciati_user2: [
device_tracker.google_maps_105790704769903066698,
device_tracker.life360_xxxxxxxx,
sensor.tracker_itag_xxxxxx,
sensor.tracker_nut_user2,
device_tracker.nut_mini_xxxxxxxx
]

### Se utilizzate il tracker ESP32 con Ble2Mqtt specificate il nome dei tracker ed i Topic MQTT

#nome_dispositivo_nut_tracker_user1: "Tracker Nut Utente1"
#topic_dispositivo_nut_tracker_user1: "xxxxxx/sensor/casa/xxxxxx/state"

#nome_dispositivo_nut_tracker_user2: "Tracker Nut Utente2"
#topic_dispositivo_nut_tracker_user2: "xxxxxx/sensor/casa/xxxxxx/state"


topic_dispositivo_ESP32_availability: "dss_ble2mqtt/30C40A24/availability"

nome_dispositivo_iTag_tracker_user1: "Tracker iTag Ingrid"
topic_dispositivo_iTag_tracker_user1: "dss_ble2mqtt/30C40A24/casa/ffffc104be21/state"
nome_dispositivo_nut_tracker_user1: "Tracker NUT Ingrid"
topic_dispositivo_nut_tracker_user1: "dss_ble2mqtt/30C40A24/casa/d9c86ac45c0f/state"
rssi_dispositivo_nut_tracker_user1: "dss_ble2mqtt/30C40A24/casa/d9c86ac45c0f/rssi"

nome_dispositivo_iTag_tracker_user2: "Tracker iTag xxxxxxxxx"
topic_dispositivo_iTag_tracker_user2: "dss_ble2mqtt/30C40A24/casa/ffffc1050d19/state"
nome_dispositivo_nut_tracker_user2: "Tracker NUT xxxxxxxxx"
topic_dispositivo_nut_tracker_user2: "dss_ble2mqtt/30C40A24/casa/f5e70469350f/state"
rssi_dispositivo_nut_tracker_user2: "dss_ble2mqtt/30C40A24/casa/f5e70469350f/rssi"

nome_dispositivo_iTag_tracker_user3: "Tracker iTag Casa"
topic_dispositivo_iTag_tracker_user3: "dss_ble2mqtt/30C40A24/casa/ffff10150422/state"

nome_dispositivo_nut_tracker_user3: "Tracker Nut xxxxxxx"
topic_dispositivo_nut_tracker_user3: "dss_ble2mqtt/30C40A24/casa/c89347a22892/state"
rssi_dispositivo_nut_tracker_user3: "dss_ble2mqtt/30C40A24/casa/c89347a22892/rssi"

nome_dispositivo_nut_tracker_user4: "Tracker Nut xxxxxxxxxxx"
topic_dispositivo_nut_tracker_user4: "dss_ble2mqtt/30C40A24/casa/f6f18c380984/state"
rssi_dispositivo_nut_tracker_user4: "dss_ble2mqtt/30C40A24/casa/f6f18c380984/rssi"
#####################################################################################

dss_options_elenco_suonerie_gateway1: [
 "0 - Police car 1", 
 "1 - Police car 2", 
 "2 - Accident", 
 "3 - Countdown", 
 "4 - Ghost", 
 "5 - Sniper rifle", 
 "6 - Battle", 
 "7 - Air raid",
 "8 - Bark",
 "10 - Doorbell",
 "11 - Knock at a door",
 "12 - Amuse",
 "13 - Alarm clock",
 "20 - MiMix",
 "21 - Enthusiastic",
 "22 - GuitarClassic",
 "23 - IceWorldPiano",
 "24 - LeisureTime",
 "25 - ChildHood",
 "26 - MorningStreamLiet",
 "27 - MusicBox",
 "28 - Orange",
 "29 - Thinker",
 "10001 - sound",
 "10002 - sound",
 "10003 - Disarm Buona Perman",
 "10004 - Promem All Armato",
 "10005 - sound",
 "10006 - sound",
 "10007 - sound",
 "10008 - Attiv All In Corso",
 "10009 - sound",
 "10010 - sound",
 "10011 - sound",
 "10012 - sound",
 "10013 - sound",
 "10014 - sound",
 "10015 - sound",
 "10016 - sound",
 "10017 - sound",
 "10018 - sound",
 "10019 - sound",
 "10020 - Attiv All In Casa",
 "10021 - sound Bip All Attiv",
 "10022 - sound",
 "10023 - Bip Bip All Attiv",
 "10024 - sound",
 "10025 - sound",
 "10026 - sound",
 "10027 - sound",
 "10028 - sound",
 "10029 - sound",
 "10030 - sound",
 "10031 - sound",
 "10032 - sound",
 "10033 - sound",
 "10034 - sound",
 "10035 - sound",
 "10036 - sound",
 "10037 - sound",
 "10038 - sound",
 "10039 - sound",
 "10040 - sound",
 "10041 - sound",
 "10042 - sound",
 "10043 - sound",
 "10044 - sound",
 "10045 - sound",
 "10046 - sound",
 "10047 - sound",
 "10048 - sound",
 "10049 - sound",
 "10050 - sound"
]

entity_sensore_blindata_pt: binary_sensor.door_window_sensor_158d0002e8b33c
entity_sensore_fin_salotto_pt: binary_sensor.door_window_sensor_158d0002e8c6ab
entity_sensore_fin_letto_pt: binary_sensor.door_window_sensor_158d0002c15862
entity_sensore_fin_letto_bimbi_pt: binary_sensor.door_window_sensor_158d0002c156df
entity_sensore_fin_cucina_pt: binary_sensor.door_window_sensor_158d0002e8b2f3
entity_sensore_fin_bagno_pt: binary_sensor.door_window_sensor_158d0002c15798


# ### Nome del Gruppo dei dispositivi dell'utente 3. Deve cominciare con "Dispositivi "
nome_gruppo_dispositivi_utente3: "Dispositivi xxxxxxxxxx" 

### Entity_id di un device_tracker o di un gruppo di device_tracker che devono essere tracciati per l'utente 3
elenco_dispositivi_tracciati_user3: [
device_tracker.life360_xxxxxxxx,
device_tracker.g6_fritz_box,
sensor.tracker_nut_user3,
device_tracker.nut_mini_xxxxxxx
]


# ### Nome del Gruppo dei dispositivi dell'utente 3. Deve cominciare con "Dispositivi "
nome_gruppo_dispositivi_utente4: "Dispositivi yyyyyyyyy" 

### Entity_id di un device_tracker o di un gruppo di device_tracker che devono essere tracciati per l'utente 4
elenco_dispositivi_tracciati_user4: [
device_tracker.life360_yyyyyyyyy,
device_tracker.galaxy_j7_2016_fritz_box,
sensor.tracker_nut_user4,
device_tracker.nut_mini_yyyyyyyyy
]


#----------------------------------------------------------------------------------------------------#
# Le entità (entity_id, o friendly_name) vanno inserite come segue ["entità","entià2","ultima entità"]
# L'insieme dell'entità va tra prentesi quadre, e ognuna di esse va all'interno delle virgolette
# separate dalla virgola, eccetto per l'ultima o unica uenità.
#----------------------------------------------------------------------------------------------------#
location_tracker_hub: [
  "person.ingrid",
  "person.xxxxxx"
]

#----------------------------------------------------------------------------------------------------#
# Inserire i propri dispositivi GOOGLE e/o GROUP con il proprio friandly_name
#----------------------------------------------------------------------------------------------------#
notification_media_player_google_hub: [
  "Google Home"
]

#----------------------------------------------------------------------------------------------------#
# Inserire i propri dispositivi ALEXA e/o GROUP con il proprio friandly_name.
#----------------------------------------------------------------------------------------------------#
notification_media_player_alexa_hub: [
  "Echo Dot di Ingrid"
]

#----------------------------------------------------------------------------------------------------#
# Inserire i propri servizi di notifica   http://hassio:8123/dev-service nel campo servizio           
#                                         digita notify. (con il punto) e vedrai quali sono i tuoi    
#----------------------------------------------------------------------------------------------------#
default_notify_hub: [
  "Notifiche Telegram",
  "Ios Iphone di xxxxxxx",
  "TelegramHTML",
  "Android",
  "Test Nome NOTIFICA"
]
#ariela_tts: homeassistant/tts/android_oneplus_ariela_tts/tts