- 'Alban & Miriam - Duame.mp3'
- 'Arilena Ara - Doja.mp3'
- 'Dafina Zeqiri - Lule Lule (feat. Lumi B).mp3'
- 'Dafina Zeqiri - Vuj vuj vuj.mp3'
- 'Flori Mumajesi - Plas.mp3'
- 'Flori Mumajesi - Thjesht te du.mp3'
- 'Ghetto Geasy - Dashni me raki.mp3'
- 'John Shahu - Havana.mp3'
- 'Lumi B - Kalon.mp3'
- 'Yll Limani - Engjej.mp3'
- 'Yll Limani - Hala.mp3'